FROM python:3.9

RUN pip install pipenv

# WORKDIR /app

# COPY ./ /app

# # 事前にインストールしておきたいライブラリがある場合はrequirements.txtに記述しておくと、build時にインストールします。
# # RUN pipenv install  --dev
# RUN pip install -r requirements/dev.txt
# RUN pip install -r requirements/prod.txt
